-- Create tables for exam scheduler app
-- Run this in Supabase SQL Editor

-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) DEFAULT 'USER'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Create users sequence
CREATE SEQUENCE IF NOT EXISTS public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- Set users id default
ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

-- Create exam table
CREATE TABLE IF NOT EXISTS public.exam (
    id bigint NOT NULL,
    local_date date,
    subject character varying(255),
    user_id bigint NOT NULL
);

-- Create exam sequence
ALTER TABLE public.exam ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary keys
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exam
    ADD CONSTRAINT exam_pkey PRIMARY KEY (id);

-- Add unique constraint
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

-- Add foreign key
ALTER TABLE ONLY public.exam
    ADD CONSTRAINT fkemywihfkga7ba286m04l0fwdo FOREIGN KEY (user_id) REFERENCES public.users(id);

-- Insert users data
INSERT INTO public.users (id, name, email, password, role, created_at) VALUES
(2, 'Antonio', 'antonio@example.com', '$2a$10$xACFN9D6Mu6PwbbFWo2BDeH6obwQyBwfwYDcK8YyCtx2XWQ7ghu6y', 'USER', '2025-07-05 14:29:08.690224'),
(3, 'toni', 'toni@gmail.com', '$2a$10$Conf4VQlgzZtiIJ1lDE09uHm52fCZ.1NHOQFCfQ58MXtZNso1906.', 'USER', '2025-07-07 19:20:37.396847'),
(4, 'John', 'john@user.com', '$2a$10$Q6iqRI1MmF.IIuUgP3a2WeWVxdDVlzF0eHFaK/aaQ2oq9g8pShfAy', 'USER', '2025-07-07 19:26:48.613292'),
(5, 'ionut', 'ionsmecheru99@gmail.com', '$2a$10$3m.C0h60qwiFhcn90cs9NetEe8W08d8Sv2tQD8V/O63P//dpvz3X2', 'USER', '2025-08-08 13:00:24.505772'),
(6, 'gigel', 'gigel@frone.com', '$2a$10$PYRzAxH7wD4rW9EvBtGmJOvC6ZGdLAcCsyxEFvlVg8fptFY9yKLYK', 'USER', '2025-08-09 10:48:58.052183'),
(7, 'sefulthau', 'sefubanilor@yahoo.com', '$2a$10$kkV0mS.xyWuzYfMYx4eoHuK0b6J0LUzIsG54BVozZoki7MFnms8Ky', 'USER', '2025-08-09 10:56:28.58832');

-- Insert exam data
INSERT INTO public.exam (id, local_date, subject, user_id) VALUES
(10, '2025-08-29', 'Algebra', 3),
(11, '2025-08-18', 'franceza', 3),
(12, '2025-09-06', 'Matematici Speciale', 3),
(13, '2025-08-20', 'Geografie', 5);

-- Update sequences to current values
SELECT pg_catalog.setval('public.users_id_seq', 7, true);
SELECT pg_catalog.setval('public.exam_id_seq', 13, true);